// Package dbinit bootstraps the bundled MariaDB runtime: datadir install,
// random credentials, database creation and the ordered SQL import pipeline.
package dbinit

import (
	"crypto/rand"
	"database/sql"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"sort"
	"strings"

	_ "github.com/go-sql-driver/mysql"

	"github.com/gswxy/gswxy-realm/manager/internal/logging"
	"github.com/gswxy/gswxy-realm/manager/internal/platform"
)

// Credentials are stored with mode 0600 in var/state/.
type Credentials struct {
	Root     string `json:"root"`
	App      string `json:"app"`
	Port     int    `json:"port"`
	Username string `json:"username"`
}

// Databases created for AzerothCore + Playerbots.
var Databases = []string{"acore_auth", "acore_characters", "acore_world", "acore_playerbots"}

const appUser = "acore"

func RandomPassword(n int) string {
	raw := make([]byte, n*3/4+1)
	_, _ = rand.Read(raw)
	s := base64.RawURLEncoding.EncodeToString(raw)
	return s[:n] + "aA1!" // satisfy any policy; still high entropy
}

// BootstrapPrepare is phase A of first-run database setup: install the
// datadir, write my.cnf and generate credentials. Everything needed
// BEFORE mariadbd can start. Idempotent on an initialized datadir.
func BootstrapPrepare(p platform.Paths, log *logging.Logger, st StateRecorder,
	mysqldBin, installDbBin string, progress func(step string)) (*Credentials, error) {

	if err := os.MkdirAll(p.MySQLData(), 0o750); err != nil {
		return nil, err
	}
	// mariadb needs a writable tmp area of its own.
	if err := os.MkdirAll(filepath.Join(p.Var, "mysql-tmp"), 0o750); err != nil {
		return nil, err
	}

	creds, err := LoadCreds(p)
	if err != nil {
		return nil, err
	}

	if creds == nil {
		// Fresh credentials + a random high port; persisted 0600.
		port, err := freePort()
		if err != nil {
			return nil, err
		}
		creds = &Credentials{
			Root:     RandomPassword(32),
			App:      RandomPassword(32),
			Port:     port,
			Username: appUser,
		}
		if err := saveCreds(p, creds); err != nil {
			return nil, err
		}
		log.Info("generated new database credentials (port %d)", port)
	}
	st.SetDBPort(creds.Port)
	// my.cnf must exist BEFORE runInstallDB / mariadbd reference it.
	if err := writeMyCnf(p, creds); err != nil {
		return nil, err
	}

	if !datadirInitialized(p.MySQLData()) {
		progress("installing datadir")
		if err := runInstallDB(p, installDbBin); err != nil {
			return nil, fmt.Errorf("mariadb-install-db: %w", err)
		}
	}
	return creds, nil
}

// writeMyCnf renders the generated server config consumed by mariadbd.
func writeMyCnf(p platform.Paths, creds *Credentials) error {
	cnf := fmt.Sprintf(`# Generated by GSWXY Manager — 绑定 127.0.0.1，不对外暴露
[mysqld]
datadir                    = %s
tmpdir                     = %s
port                       = %d
bind_address               = 127.0.0.1
socket                     = %s
skip_name_resolve
character_set_server       = utf8mb4
collation_server           = utf8mb4_unicode_ci
max_allowed_packet         = 1G
innodb_buffer_pool_size    = 512M
innodb_flush_method        = O_DIRECT
innodb_log_file_size       = 128M
slow_query_log_file        = %s
long_query_time            = 5
plugin_dir                 = %s
`, p.MySQLData(), filepath.Join(p.Var, "mysql-tmp"), creds.Port,
		filepath.Join(p.Var, "mysql.sock"),
		filepath.Join(p.Logs(), "mariadb-slow.log"),
		filepath.Join(p.MySQLRuntime(), "lib", "plugin"))
	if err := os.MkdirAll(filepath.Dir(myCnfPath(p)), 0o700); err != nil {
		return err
	}
	// 0600: the file itself carries no secret but must not be world-writable.
	return os.WriteFile(myCnfPath(p), []byte(cnf), 0o600)
}

func datadirInitialized(dir string) bool {
	for _, marker := range []string{"mysql", "performance_schema", "aria_log_control"} {
		if _, err := os.Stat(filepath.Join(dir, marker)); err == nil {
			return true
		}
	}
	return false
}

func runInstallDB(p platform.Paths, installDbBin string) error {
	args := []string{
		"--defaults-file=" + myCnfPath(p),
		"--datadir=" + p.MySQLData(),
		"--basedir=" + p.MySQLRuntime(),
		"--auth-root-authentication-method=normal",
		"--skip-test-db",
	}
	cmd := command(installDbBin, args)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// myCnfPath is where the Manager writes the generated my.cnf.
func myCnfPath(p platform.Paths) string { return filepath.Join(p.State(), "my.cnf") }

// MyCnfPath is exported for the supervisor launcher.
func MyCnfPath(p platform.Paths) string { return myCnfPath(p) }

// LoadCreds reads existing credentials, if any.
func LoadCreds(p platform.Paths) (*Credentials, error) {
	raw, err := os.ReadFile(p.DBCreds())
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	c := &Credentials{}
	if err := json.Unmarshal(raw, c); err != nil {
		return nil, err
	}
	return c, nil
}

func saveCreds(p platform.Paths, c *Credentials) error {
	if err := os.MkdirAll(p.State(), 0o700); err != nil {
		return err
	}
	raw, _ := json.MarshalIndent(c, "", "  ")
	// 0600: database secrets must not be group/world readable.
	return os.WriteFile(p.DBCreds(), raw, 0o600)
}

// ProvisionAccounts is phase B (after mariadbd is up): set the root
// password on a fresh datadir, then create the databases and the
// least-privilege app user. Safe to re-run.
func ProvisionAccounts(p platform.Paths, creds *Credentials, log *logging.Logger) error {
	if err := setRootPassword(creds, log); err != nil {
		return err
	}
	dsn := fmt.Sprintf("root:%s@tcp(127.0.0.1:%d)/?charset=utf8mb4&multiStatements=true", creds.Root, creds.Port)
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		return err
	}
	defer db.Close()

	for _, name := range Databases {
		q := fmt.Sprintf("CREATE DATABASE IF NOT EXISTS `%s` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", name)
		if _, err := db.Exec(q); err != nil {
			return fmt.Errorf("create %s: %w", name, err)
		}
		// AC 标准的更新跟踪表（worldserver 自动更新器与导入管线共用）。
		tq := "CREATE TABLE IF NOT EXISTS `" + name + "`.`updates` (" +
			"`name` VARCHAR(200) NOT NULL, `hash` CHAR(40) DEFAULT '', " +
			"`state` ENUM('RELEASED','CUSTOM','MODULE','ARCHIVED','PENDING') NOT NULL DEFAULT 'RELEASED', " +
			"`timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, " +
			"`speed` INT UNSIGNED NOT NULL DEFAULT 0, PRIMARY KEY(`name`)) " +
			"ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
		if _, err := db.Exec(tq); err != nil {
			return fmt.Errorf("create updates table in %s: %w", name, err)
		}
	}
	// App user: localhost only, least privilege on the AC databases.
	stmts := []string{
		fmt.Sprintf("CREATE USER IF NOT EXISTS `%s`@`localhost` IDENTIFIED BY '%s'", appUser, creds.App),
		fmt.Sprintf("CREATE USER IF NOT EXISTS `%s`@`127.0.0.1` IDENTIFIED BY '%s'", appUser, creds.App),
	}
	for _, name := range Databases {
		stmts = append(stmts,
			fmt.Sprintf("GRANT ALL PRIVILEGES ON `%s`.* TO `%s`@`localhost`", name, appUser),
			fmt.Sprintf("GRANT ALL PRIVILEGES ON `%s`.* TO `%s`@`127.0.0.1`", name, appUser))
	}
	for _, s := range stmts {
		if _, err := db.Exec(s); err != nil {
			return fmt.Errorf("provision: %w", err)
		}
	}
	if _, err := db.Exec("FLUSH PRIVILEGES"); err != nil {
		return err
	}
	log.Info("databases and app user provisioned")
	return nil
}

// setRootPassword authenticates as root on a fresh datadir (empty
// password thanks to --auth-root-authentication-method=normal) and
// secures EVERY root@host account. MariaDB 10.4+ ships combined-plugin
// accounts (unix_socket OR password) where bare ALTER USER fails with
// ER_CANNOT_USER 1396 — set the plugin explicitly, and drop accounts
// that refuse (hardening: fewer remote root entries is better). The
// Manager itself always connects over TCP 127.0.0.1, so that account
// is guaranteed to exist with the final password.
func setRootPassword(creds *Credentials, log *logging.Logger) error {
	dsn := fmt.Sprintf("root@tcp(127.0.0.1:%d)/?charset=utf8mb4&multiStatements=true", creds.Port)
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		return err
	}
	defer db.Close()
	if err := db.Ping(); err != nil {
		// Root already password-protected: nothing to do.
		return nil
	}
	rows, err := db.Query(`SELECT Host FROM mysql.user WHERE User = 'root'`)
	if err != nil {
		return fmt.Errorf("list root accounts: %w", err)
	}
	var hosts []string
	for rows.Next() {
		var h string
		if rows.Scan(&h) == nil {
			hosts = append(hosts, h)
		}
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return err
	}
	for _, h := range hosts {
		q := fmt.Sprintf(
			"ALTER USER 'root'@'%s' IDENTIFIED VIA mysql_native_password USING PASSWORD('%s')",
			h, creds.Root)
		if _, err := db.Exec(q); err != nil {
			log.Warn("ALTER USER root@%s failed (%v), dropping the account", h, err)
			if _, derr := db.Exec(fmt.Sprintf("DROP USER 'root'@'%s'", h)); derr != nil {
				return fmt.Errorf("secure root@%s: %w", h, derr)
			}
		}
	}
	// Guarantee the TCP account the Manager itself uses.
	if _, err := db.Exec(fmt.Sprintf(
		"CREATE USER IF NOT EXISTS 'root'@'127.0.0.1' IDENTIFIED VIA mysql_native_password USING PASSWORD('%s')",
		creds.Root)); err != nil {
		return fmt.Errorf("ensure root@127.0.0.1: %w", err)
	}
	if _, err := db.Exec("FLUSH PRIVILEGES"); err != nil {
		return err
	}
	log.Info("root password configured (%d root accounts processed)", len(hosts))
	return nil
}

// SQLFile is one file in the import pipeline.
type SQLFile struct {
	Path     string
	Database string
	Label    string
	// CheckUpdates: the file is an upstream dated update; skip it when
	// the target database's `updates` table already records it (AC
	// convention: ARCHIVED entries are already merged into the base
	// snapshot), and record newly applied ones so the worldserver
	// auto-updater does not re-apply them.
	CheckUpdates bool
}

// BuildPipeline assembles the ordered SQL import plan:
// base -> core updates -> playerbots module SQL -> GSWXY locale.
func BuildPipeline(p platform.Paths) []SQLFile {
	var files []SQLFile
	add := func(dir, db, label string) {
		if fs, err := walkSQL(dir); err == nil {
			for _, f := range fs {
				files = append(files, SQLFile{Path: f, Database: db, Label: label})
			}
		}
	}
	// Base snapshots only — dated updates are applied by the worldserver
	// auto-updater on first start (the canonical AC flow: it creates the
	// updates tracking tables, skips ARCHIVED entries and records what it
	// applies). Importing updates here would fight that machinery.
	base := p.SQLDir()
	add(filepath.Join(base, "base", "db_auth"), "acore_auth", "core/base")
	add(filepath.Join(base, "base", "db_characters"), "acore_characters", "core/base")
	add(filepath.Join(base, "base", "db_world"), "acore_world", "core/base")

	// Module base dumps. Never walk create/ (destructive DROP helpers),
	// archive/ (squashed updates) or custom/ (operator content).
	mod := filepath.Join(p.AppDest, "modules", "mod-playerbots", "data", "sql")
	add(filepath.Join(mod, "playerbots", "base"), "acore_playerbots", "playerbots")
	add(filepath.Join(mod, "characters", "base"), "acore_characters", "playerbots")
	add(filepath.Join(mod, "world", "base"), "acore_world", "playerbots")

	// GSWXY zhCN locale: world/ targets the world DB (base-column UPDATEs),
	// playerbots/ targets the characters DB (bot name pools). The import
	// client runs each file against its mapped database.
	add(filepath.Join(p.LocaleDir(), "world"), "acore_world", "locale/zhCN")
	add(filepath.Join(p.LocaleDir(), "playerbots"), "acore_characters", "locale/zhCN")
	return files
}

func walkSQL(dir string) ([]string, error) {
	var out []string
	walkErr := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			if os.IsNotExist(err) {
				return nil
			}
			return err
		}
		if info.Mode().IsRegular() && strings.HasSuffix(info.Name(), ".sql") {
			out = append(out, path)
		}
		return nil
	})
	sort.Strings(out)
	return out, walkErr
}

func freePort() (int, error) {
	l, err := netListen("tcp", "127.0.0.1:0")
	if err != nil {
		return 0, err
	}
	defer l.Close()
	tcp, ok := l.Addr().(*net.TCPAddr)
	if !ok {
		return 0, fmt.Errorf("no tcp addr")
	}
	return tcp.Port, nil
}

// StateRecorder avoids an import cycle with package state.
type StateRecorder interface {
	SetDBPort(port int) error
}
