// Package version resolves build metadata from build-info.json.
package version

import (
	"encoding/json"
	"os"
	"strings"
)

// Info mirrors build-info.json generated by CI.
type Info struct {
	Product         string `json:"product"`
	Version         string `json:"version"`
	Channel         string `json:"channel"` // stable | nightly | dev
	Core            struct {
		Repository string `json:"repository"`
		Branch     string `json:"branch"`
		Commit     string `json:"commit"`
	} `json:"core"`
	Playerbots struct {
		Repository string `json:"repository"`
		Branch     string `json:"branch"`
		Commit     string `json:"commit"`
	} `json:"playerbots"`
	ClientData struct {
		Version string `json:"version"`
	} `json:"client_data"`
	DatabaseRuntime struct {
		Flavor  string `json:"flavor"`
		Version string `json:"version"`
	} `json:"database_runtime"`
	Locale struct {
		Language string `json:"language"`
		Version  string `json:"version"`
	} `json:"locale"`
	Build struct {
		RunID   string `json:"run_id"`
		BuiltAt string `json:"built_at"`
	} `json:"build"`
}

// Dev returns placeholder info for source builds.
func Dev() Info {
	i := Info{Product: "GSWXY Realm", Version: "0.0.0-dev", Channel: "dev"}
	i.Core.Commit = "unknown"
	i.Playerbots.Commit = "unknown"
	return i
}

// Load reads build-info.json; missing file falls back to dev info.
func Load(path string) Info {
	raw, err := os.ReadFile(path)
	if err != nil {
		return Dev()
	}
	i := Dev()
	if err := json.Unmarshal(raw, &i); err != nil {
		return Dev()
	}
	return i
}

// Compare 语义化版本比较：a<b 返回 -1，相等 0，a>b 返回 1。
// 非语义化版本（无法解析）按字符串比较处理；带 -nightly 等预发布
// 后缀时，同版本号下预发布版视为更旧（semver 惯例）。
func Compare(a, b string) int {
	pa, aok := parseSemver(a)
	pb, bok := parseSemver(b)
	if !aok && !bok {
		if a == b {
			return 0
		}
		if a < b {
			return -1
		}
		return 1
	}
	if !aok {
		return -1
	}
	if !bok {
		return 1
	}
	for i := 0; i < 3; i++ {
		if pa.nums[i] != pb.nums[i] {
			if pa.nums[i] < pb.nums[i] {
				return -1
			}
			return 1
		}
	}
	// 主版本相同：无预发布后缀 > 有后缀；都有后缀按字典序。
	switch {
	case pa.pre == "" && pb.pre == "":
		return 0
	case pa.pre == "":
		return 1
	case pb.pre == "":
		return -1
	case pa.pre < pb.pre:
		return -1
	case pa.pre > pb.pre:
		return 1
	}
	return 0
}

type semver struct {
	nums [3]int
	pre  string
}

func parseSemver(v string) (semver, bool) {
	s := strings.TrimSpace(v)
	s = strings.TrimPrefix(s, "v")
	dash := strings.IndexAny(s, "-+")
	pre := ""
	if dash >= 0 {
		pre = s[dash+1:]
		if plus := strings.Index(pre, "+"); plus >= 0 {
			pre = pre[:plus]
		}
		s = s[:dash]
	}
	parts := strings.Split(s, ".")
	if len(parts) > 3 {
		return semver{}, false
	}
	out := semver{pre: pre}
	for i, p := range parts {
		if p == "" {
			return semver{}, false
		}
		n := 0
		for _, c := range p {
			if c < '0' || c > '9' {
				return semver{}, false
			}
			n = n*10 + int(c-'0')
		}
		out.nums[i] = n
	}
	return out, true
}
