// Package version resolves build metadata from build-info.json.
package version

import (
	"encoding/json"
	"os"
)

// Info mirrors build-info.json generated by CI.
type Info struct {
	Product         string `json:"product"`
	Version         string `json:"version"`
	Channel         string `json:"channel"` // stable | nightly | dev
	Core            struct {
		Repository string `json:"repository"`
		Branch     string `json:"branch"`
		Commit     string `json:"commit"`
	} `json:"core"`
	Playerbots struct {
		Repository string `json:"repository"`
		Branch     string `json:"branch"`
		Commit     string `json:"commit"`
	} `json:"playerbots"`
	ClientData struct {
		Version string `json:"version"`
	} `json:"client_data"`
	DatabaseRuntime struct {
		Flavor  string `json:"flavor"`
		Version string `json:"version"`
	} `json:"database_runtime"`
	Locale struct {
		Language string `json:"language"`
		Version  string `json:"version"`
	} `json:"locale"`
	Build struct {
		RunID   string `json:"run_id"`
		BuiltAt string `json:"built_at"`
	} `json:"build"`
}

// Dev returns placeholder info for source builds.
func Dev() Info {
	i := Info{Product: "GSWXY Realm", Version: "0.0.0-dev", Channel: "dev"}
	i.Core.Commit = "unknown"
	i.Playerbots.Commit = "unknown"
	return i
}

// Load reads build-info.json; missing file falls back to dev info.
func Load(path string) Info {
	raw, err := os.ReadFile(path)
	if err != nil {
		return Dev()
	}
	i := Dev()
	if err := json.Unmarshal(raw, &i); err != nil {
		return Dev()
	}
	return i
}
